#!/bin/bash
#

USER="admin"
PASS=""
HURL="https://registry.idocker.io"
MTAG=$2
CONTAIN=$3

function usage() {
cat << HELP

docker-tag  --  list all tags for a Docker image on a remote registry

EXAMPLE:
    - list all tags for ubuntu:
       docker-tag tags ubuntu

    - list all php tags containing apache:
       docker-tag tags php apache

    - list all images of harbor:
       docker-tag get_images

    - list all tags for harbor redis:
       docker-tag get_tags redis/redis

HELP
}

if [ $# -lt 1 ]; then
    usage
	  exit 2
fi

function tags() {
    TAGS=$(curl -ksL https://registry.hub.docker.com/v1/repositories/${MTAG}/tags | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}')
    if [ "${CONTAIN}" != "" ]; then
        echo -e $(echo "${TAGS}" | grep "${CONTAIN}") | tr ' ' '\n'
    else
        echo "${TAGS}"
    fi
}

function get_images() {
    PROJECTS=$(curl -k -s -u ${USER}:${PASS} -X GET "${HURL}/api/v2.0/projects?page=1&page_size=30&with_tag=true" | jq . | grep \"name\" | awk -F '"' '{print $4}')
    for p in ${PROJECTS}; do
        REPOS=$(curl -k -s -u ${USER}:${PASS} -X GET "${HURL}/api/v2.0/projects/${p}/repositories?page_size=50" -H "accept: application/json" | jq . | grep \"name\" | awk -F '"' '{print $4}')
        # here sed
        echo ${REPOS} | sed 's/ /\n/g '
    done
}

function get_tags() {
    PROJECT=$(echo ${MTAG} | awk -F'/' '{print $1}')
    REPO=$(echo ${MTAG} | awk -F'/' '{print $2}')
    TAG=$(curl -k -s -u ${USER}:${PASS} -X GET "${HURL}/api/v2.0/projects/${PROJECT}/repositories/${REPO}/artifacts?page=1&page_size=30&with_tag=true" -H  "accept: application/json" | jq . | grep \"name\" | awk -F '"' '{print $4}')
    # here tr
    echo ${TAG} | tr ' ' '\n'
}

case $1 in
    get_images)
        get_images
        ;;
    get_tags)
        get_tags
        ;;
    tags)
        tags
        ;;
    *)
        usage
        ;;
esac
